### ISSUE TITLE
Multiple files upload not working

### ISSUE THREAD

**Issue by comzeradd** [udx/wp-stateless-gravity-forms-addon#10]
Hi,

When enabling "Multiple Files" on a File field, uploading files doesn't work and raises and exception.

```
"NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, stdClass given in wp-content/plugins/wp-stateless/lib/classes/compatibility/gravity-forms.php:92"
"Stack trace:"
"#0 wp-content/plugins/wp-stateless/lib/classes/compatibility/gravity-forms.php(92): strpos()"
"#1 wp-includes/class-wp-hook.php(326): wpCloud\StatelessMedia\GravityForm->gform_save_field_value()"
"#2 wp-includes/plugin.php(205): WP_Hook->apply_filters()"
"#3 wp-content/plugins/gravityforms/gravityforms.php(7032): apply_filters()"
"#4 wp-content/plugins/gravityforms/forms_model.php(3488): gf_apply_filters()"
"#5 wp-content/plugins/gravityforms/forms_model.php(3361): GFFormsModel::get_prepared_input_value()"
"#6 wp-content/plugins/gravityforms/forms_model.php(6855): GFFormsModel::create_lead()"
"#7 wp-content/plugins/gravityforms/..."
```

This is tested with Gravity Forms `2.8.13`. I know [documentation](https://stateless.udx.io/addons/gravity-forms/) says latest tested version is `2.7.17.1`, but that's a really old version and didn't have that available to test it.

**Comment by planv** [comment]
Hello @comzeradd 

Do you use this Addon `WP-Stateless – Gravity Forms Addon` https://wordpress.org/plugins/wp-stateless-gravity-forms-addon/ ?

It has compatibility with `Gravity Forms` plugin version `2.8.9`  


----

We will update information here https://stateless.udx.io/addons/gravity-forms/ soon, thanks for pointing this out.

**Comment by comzeradd** [comment]
I just installed the addon and re-tried. I'm still getting a similar error but it's now triggered by the addon code.

```
"NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, stdClass given in /wp-content/plugins/wp-stateless-gravity-forms-addon/class-gravity-forms.php:93"
"Stack trace:"
"#0 /wp-content/plugins/wp-stateless-gravity-forms-addon/class-gravity-forms.php(93): strpos()"
"#1 /wp-includes/class-wp-hook.php(326): SLCA\GravityForms\GravityForms->gform_save_field_value()"
"#2 /wp-includes/plugin.php(205): WP_Hook->apply_filters()"
"#3 /wp-content/plugins/gravityforms/gravityforms.php(7032): apply_filters()"
"#4 /wp-content/plugins/gravityforms/forms_model.php(3488): gf_apply_filters()"
"#5 /wp-content/plugins/gravityforms/forms_model.php(3361): GFFormsModel::get_prepared_input_value()"
"#6 /wp-content/plugins/gravityforms/forms_model.php(6855): GFFormsModel::create_lead()"
"#7 /wp-content/plugins/gravityforms/incl..."
```

**Comment by comzeradd** [comment]
Hi,

Should I give it another try? I noticed https://github.com/udx/wp-stateless-gravity-forms-addon/pull/11 but not sure if it related to this bug.

Thanks

**Comment by comzeradd** [comment]
Everything works fine now after latest changes
